version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=crawler_db
    depends_on:
      - redis
      - mysql
    expose:
      - 9000
    command: php-fpm

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - api
    environment:
      - NGINX_WORKER_PROCESSES=4
      - NGINX_WORKER_CONNECTIONS=2048

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=crawler_db
    depends_on:
      - redis
      - mysql
    command: php artisan queue:work --queue=crawler_task_queue --tries=3

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=crawler_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: